### ISSUE TITLE
Remarkable FACS rewrite

### ISSUE THREAD

**Issue by brainstorm** [brentp/pybloomfaster#4]
Brent,

I really like your rewrite on FACS:

https://github.com/scilifelab/facs

You managed to cut through the cruft of our implementation with cython, well done!

Did you run some benchmarks you can share with us? I'm very curious about how it performs with cython instead of plain `C-extensions` as we did.

Kudos!
Roman

@arvestad, @henrikstranneheim, @guillermo-carrasco, @tzcoolman

**Comment by brentp** [comment]
Hi @brainstorm , I hadn't seen FACS, I just pulled the files from Bloom::Faster on CPAN. Are you the author(s) of Bloom::Faster as well?

I don't have any benchmarks, I ran some back in 2010, but haven't had use for it since. Assuming I've done the cython correctly, the performance should be similar--assuming the underlying C hasn't changed much.

**Comment by brainstorm** [comment]
Aha, I see, sorry, the codebase and python extensions were so familiar (yours being much cleaner, btw). No, I'm not the author of Bloom::Faster, but we used that core as well for FACS :)

Just curious, how come you do not use pybloomfaster anymore? Did you find a faster alternative for your day-to-day filtering?

**Comment by brentp** [comment]
I just haven't had much use for bloomfilters since then. Once I do, I might be inclined to use a more active project like yours or the one from bit.ly. Though it would be interesting to see a speed comparison.

**Comment by brainstorm** [comment]
Been there with `dablooms` (if that's the one you're referring to from bit.ly):

https://github.com/brainstorm/dablooms/blob/master/pydablooms/dna_pydablooms.py

When building (big) bloom filters such as `hg19`, errors like these occur:

```
Error, 4 bit int Overflow
Error, 4 bit int Overflow
Error, 4 bit int Overflow
```

The reason is that there are a lot of kmers that need to be bloom.add-ed to the filter and the 4-bit counter overflows.

That comes from the "counting bloom filter" functionality, which we don't need. But removing this feature and making it optional when running with "big" datasets might be time consuming.

For some ongoing automated benchmarks (still WIP), you might want to have a look here (scroll down, it's bowtie1 vs FACS):

http://nbviewer.ipython.org/github/brainstorm/facs/blob/269f1da73/facs/utils/benchmarks_facs.ipynb?create=1
